name: CI

on:
  push:
    branches: [ "master" ]
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - tree-sitter.json
  pull_request:
    branches: [ "master" ]
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - tree-sitter.json

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]

    steps:
    - uses: actions/checkout@v4
    - name: Set up tree-sitter
      uses: tree-sitter/setup-action/cli@v2
    - name: Run tests
      uses: tree-sitter/parser-test-action@v2
    - name: Parse sample files
      uses: tree-sitter/parse-action@v4
      id: parse-files
      with:
        files: examples/**
